# Generated by Django 6.0.4 on 2026-04-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categoriëen',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('contactpersoon', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefoon', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Leverancier',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('dosering', models.CharField(max_length=200)),
                ('voorraad', models.PositiveIntegerField(default=0)),
                ('minimum_voorraad', models.PositiveIntegerField(default=10)),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('omschrijving', models.TextField(blank=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
                ('vereist_recept', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
            options={
                'verbose_name': 'Medecijn',
                'verbose_name_plural': 'Medecijnen',
            },
        ),
    ]
