# Generated by Django 6.0.4 on 2026-04-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_leverancier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicijn', 'verbose_name_plural': 'Medicijnen'},
        ),
    ]
