# Generated by Django 6.0.4 on 2026-04-26 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arts_naam', models.CharField(max_length=200)),
                ('arts_telefoon', models.CharField(max_length=20)),
                ('datum', models.DateField()),
                ('notities', models.TextField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('in_behandeling', 'Im behandeling'), ('klaar', 'Klaar'), ('uitgeleverd', 'Uitgeleverd'), ('geannuleerd', 'Geannuleerd')], default='nieuw', max_length=20)),
                ('klant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recept',
                'verbose_name_plural': 'Recepten',
                'ordering': ['-aangemaakt_op'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoeveelheid', models.PositiveIntegerField()),
                ('instructies', models.TextField(blank=True)),
                ('medicijn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.medicine')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Regels', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Receptregel',
            },
        ),
    ]
