# Generated by Django 6.0.4 on 2026-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notities',
            field=models.TextField(blank=True),
        ),
    ]
