# Generated by Django 6.0.4 on 2026-05-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_notities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regels', to='prescriptions.prescription'),
        ),
    ]
