# Generated by Django 6.0.4 on 2026-04-26 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geboortedafum', models.DateField(blank=True, null=True)),
                ('telefoon', models.CharField(blank=True, max_length=20)),
                ('adres', models.TextField(blank=True)),
                ('allergiëen', models.TextField(blank=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klantprofiel',
            },
        ),
    ]
