# Generated by Django 6.0.4 on 2026-04-27 10:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bsn',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='9 cijfers', null=True),
        ),
    ]
