# Generated by Django 6.0.4 on 2026-04-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_bsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='geboortedafum',
            new_name='geboortedatum',
        ),
    ]
